"""slug to articles model rectification

Revision ID: 7461793b28d9
Revises: 6871f3b2721d
Create Date: 2025-05-26 10:12:37.404743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7461793b28d9'
down_revision = '6871f3b2721d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
